### ISSUE TITLE
Some import errors

### ISSUE THREAD

**Issue by ghost** [IDEALLab/airfoil-opt-gan#1]
Your idea about aerodynamic airfoil modeling using GAN is very impressive and it is an interesting topic!
 
However, I got some errors when trying to train. I think some modules, optimize_kde is not defined, and I am not sure why I got some other errors like below.

Could you help me solve these problem?
----------------------------------------------------------------------------------------------------- 

  File "train.py", line 16, in <module>
    from manifold_evaluation.likelihood import ci_mll
  File "C:\Users\h****\Desktop\airfoil-opt-gan-master\manifold_evaluation\likelihood.py", line 8, in <module>
    from utils import optimize_kde, mean_err
ImportError: cannot import name 'optimize_kde'

**Comment by wchen459** [comment]
Thanks for finding out this issue! These messages seem to be referring to one error: the method 'optimize_kde' is missing in utils.py. I have added that method, so now you should be able to get rid of the error. Let me know if there is still any problem.

**Comment by ghost** [comment]
Thank you so much for that, but I still have some issues on training. 
I don't know why it happened. Could you check this up with your most updated code? I hope all training and optimizations to work. 

-----------------------------------------------------------------------------------------------------------
(tensorflow) C:\Users\convm\Desktop\Tensorflow\airfoil-opt-gan-master>python train.py startover
Plotting training samples ...
Traceback (most recent call last):
  File "train.py", line 59, in <module>
    model.train(X_train, batch_size=batch_size, train_steps=train_steps, save_interval=args.save_interval)
  File "C:\Users\convm\Desktop\Tensorflow\airfoil-opt-gan-master\gan.py", line 195, in train
    x_fake_train, cp_train, w_train, ub_train, db_train = self.generator(self.c, self.z)
  File "C:\Users\convm\Desktop\Tensorflow\airfoil-opt-gan-master\gan.py", line 55, in generator
    cpw = tf.reshape(cpw, (-1, dim_cpw, 3, depth_cpw))
  File "C:\Users\convm\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7759, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "C:\Users\convm\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "C:\Users\convm\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

**Comment by wchen459** [comment]
I tested the code on my machine and it runs without error on python 2.7 and tensorflow 1.6.0. Can you specify your python and tensorflow version?

**Comment by wchen459** [comment]
@hkim716 I'm closing the issue for now. Let me know if there is still problem making the code work.
